source "https://rubygems.org"
gem 'github-pages'
gem 'jekyll-environment-variables'
gem 'jekyll-seo-tag'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'amp-jekyll'
gem 'jekyll-pwa-plugin'
gem 'jekyll-offline', :git => 'git://github.com/jeremiak/jekyll-offline.git'
gem 'jekyll-gist'
